version: '3'
services:
  frontend:
    image: aepp-base
    build:
      context: .
    ports: ["3080:80"]
  compiler:
    image: aeternity/aesophia_http:v6.1.0
    hostname: compiler
    ports: ["3078:3080"]
