services:
  middleware:
    # TODO: use upstream after merging https://github.com/aeternity/ae_mdw/issues/1758
    image: davidyuk/temp:mdw-dev-mode-1.97.1-oas-fix
    ports: [4000:4000, 4001:4001, 3013:3013, 3313:3313]
    volumes:
      - ./docker-compose/aeternity.yaml:/home/aeternity/aeternity.yaml
    stop_grace_period: 0s

  explorer:
    image: aeternity/aescan:0.20.0
    ports: [3070:8080]
    environment:
      - NUXT_PUBLIC_NETWORK_NAME=Local network
      - NUXT_PUBLIC_NODE_URL=http://host.docker.internal:3013
      - NUXT_PUBLIC_MIDDLEWARE_URL=http://host.docker.internal:4000
      - NUXT_PUBLIC_WEBSOCKET_URL=ws://host.docker.internal:4001/v2/websocket

  frontend:
    build: .
    ports: [3080:80]
    environment:
      - VUE_APP_NETWORK_NAME=Local network
      - VUE_APP_NODE_URL=http://localhost:3013
      - VUE_APP_MIDDLEWARE_URL=http://localhost:4000
      - VUE_APP_EXPLORER_URL=http://localhost:3070
      - VUE_APP_BACKEND_URL=http://localhost:3079

  backend:
    build: backend
    ports: [3079:80]
