version: '3'
services:
  frontend:
    image: aepp-base
    build:
      context: .
      args:
        VUE_APP_BACKEND_URL: http://localhost:3079
    ports: ["3080:80"]
  backend:
    image: aepp-base-backend
    build: backend
    ports: ["3079:80"]
