<template>
  <div class="settings-remote-connection-new">
    <header-mobile>
      <ae-button
        slot="left"
        :to="{ name: 'settings-remote-connection' }"
        plain
      >
        <ae-icon
          slot="icon"
          name="arrow"
          rotate="180"
        />
      </ae-button>
      Remote Connection
    </header-mobile>

    <div
      v-if="browserReader"
      v-show="cameraAllowed"
      class="video-wrapper"
    >
      <video ref="qrCodeVideo" />
    </div>
    <div
      v-if="!cameraAllowed"
      class="permission-denied"
    >
      We don't have access to the camera to scan a QR code.
    </div>
  </div>
</template>

<script>
import { BrowserQRCodeReader } from '@zxing/library/esm5/browser/BrowserQRCodeReader';
import { AeButton, AeIcon } from '@aeternity/aepp-components';
import HeaderMobile from '../components/HeaderMobile.vue';

export default {
  components: { HeaderMobile, AeButton, AeIcon },
  data: () => ({
    cameraAllowed: false,
    browserReader: !process.env.IS_CORDOVA && new BrowserQRCodeReader(),
  }),
  watch: {
    async cameraAllowed(value) {
      if (!value) {
        this.cancelScan();
        return;
      }

      let data;
      do {
        if (data) {
          // eslint-disable-next-line no-await-in-loop
          await this.$store.dispatch('alert', {
            title: 'Scanned QR code is wrong',
            text: 'Please make sure to scan a QR code generated by the Base æpp',
          });
        }
        // eslint-disable-next-line no-await-in-loop
        data = Buffer.from(await this.scan(), 'base64');
      } while (data.length !== 15);

      this.$store.commit('addFollower', {
        id: data.toString('base64'),
        name: prompt('Name this device') || 'Unnamed',
      });
      this.$router.push({ name: 'settings-remote-connection' });
    },
  },
  async mounted() {
    if (process.env.IS_CORDOVA) {
      await new Promise((resolve, reject) => window.QRScanner
        .prepare((error, status) => (!error && status.authorized
          ? resolve() : reject(error || new Error('Denied to use the camera')))));
      this.cameraAllowed = true;
      return;
    }

    if (navigator.permissions) {
      const status = await navigator.permissions.query({ name: 'camera' });
      this.cameraAllowed = status.state !== 'denied';
      status.onchange = () => {
        this.cameraAllowed = status.state !== 'denied';
      };
      return;
    }

    this.cameraAllowed = true;
  },
  beforeDestroy() {
    this.cancelScan();
  },
  methods: {
    async scan() {
      return process.env.IS_CORDOVA
        ? new Promise((resolve, reject) => {
          window.QRScanner.scan((error, text) => (!error && text ? resolve(text) : reject(error)));
          window.QRScanner.show();
          document.getElementById('app').style.background = 'transparent';
        })
        : (await this.browserReader.decodeFromInputVideoDevice(
          undefined,
          this.$refs.qrCodeVideo,
        )).getText();
    },
    cancelScan() {
      if (process.env.IS_CORDOVA) {
        document.getElementById('app').style.background = '';
        window.QRScanner.destroy();
      } else this.browserReader.reset();
    },
  },
};
</script>

<style lang="scss" scoped>
@import '~@aeternity/aepp-components/dist/mixins.scss';

.settings-remote-connection-new {
  display: flex;
  flex-direction: column;
  flex-grow: 1;

  .header-mobile {
    background: #fff;
  }

  .permission-denied {
    text-align: center;
    line-height: 1.56;
    padding: 0 20px;
    margin: auto;
    font-size: 18px;
  }

  .video-wrapper {
    flex-grow: 1;
    overflow: hidden;
    position: relative;

    video {
      object-fit: cover;
      position: absolute;
      width: 100%;
      height: 100%;
    }
  }
}
</style>
