<template>
  <mobile-page
    :redirect-to-on-close="{ name: 'settings-remote-connection' }"
    title="Remote Connection"
    back-button
    class="settings"
  >
    <video
      v-show="cameraAllowed"
      ref="qrCodeVideo"
    />
    <div
      v-if="!cameraAllowed"
      class="permission-denied"
    >
      We don't have access to the camera to scan a QR code.
    </div>
  </mobile-page>
</template>

<script>
import ResultMetadataType from '@zxing/library/esm5/core/ResultMetadataType'
import MobilePage from '../components/MobilePage.vue'
import QrCodeReader from '../lib/QrCodeReader'

export default {
  components: { MobilePage },
  data: () => ({
    cameraAllowed: false,
    reader: new QrCodeReader()
  }),
  watch: {
    async cameraAllowed (value) {
      if (!value) {
        this.reader.reset()
        return
      }

      while (true) {
        const result = await this.reader.decodeFromInputVideoDevice(
          {
            facingMode: 'environment',
            aspectRatio: 1,
            width: { min: 360, ideal: 720, max: 1920 },
            height: { min: 240, ideal: 720, max: 1080 }
          },
          this.$refs.qrCodeVideo)
        const data = Buffer.from(
          result.resultMetadata.get(ResultMetadataType.BYTE_SEGMENTS)[0])
        if (data.length !== 15) {
          await this.$store.dispatch('alert', {
            title: 'Scanned QR code is wrong',
            text: 'Please make sure to scan a QR code generated by the Bæse æpp'
          })
          continue
        }
        this.$store.commit('addFollower', {
          key: data.toString('base64'),
          name: prompt('Name this device') || 'Unnamed'
        })
        this.$router.push({ name: 'settings-remote-connection' })
        break
      }
    }
  },
  async mounted () {
    if (process.env.IS_CORDOVA) {
      const { permissions } = window.cordova.plugins
      await new Promise((resolve, reject) =>
        permissions.requestPermission(
          permissions.CAMERA,
          ({ hasPermission }) =>
            hasPermission ? resolve() : reject(new Error('Denied to use the camera')),
          reject))
      this.cameraAllowed = true
      return
    }

    if (navigator.permissions) {
      const status = await navigator.permissions.query({ name: 'camera' })
      this.cameraAllowed = status.state !== 'denied'
      status.onchange = () => {
        this.cameraAllowed = status.state !== 'denied'
      }
      return
    }

    this.cameraAllowed = true
  },
  beforeDestroy () {
    this.reader.reset()
  }
}
</script>

<style lang="scss" scoped>
.settings {
  .permission-denied {
    text-align: center;
    line-height: 1.56;
    padding: 60px 20px;
    font-size: 18px;
  }

  video {
    width: 100%;
  }
}
</style>
<style src="./Settings.scss" lang="scss" scoped />
