<template>
  <mobile-page
    :redirect-to-on-close="{ name: 'settings-remote-connection' }"
    title="Remote Connection"
    back-button
    class="settings"
  >
    <video
      v-show="cameraAllowed"
      ref="qrCodeVideo"
    />
    <div
      v-if="!cameraAllowed"
      class="permission-denied"
    >
      We don't have access to the camera to scan a QR code.
    </div>
  </mobile-page>
</template>

<script>
import ResultMetadataType from '@zxing/library/esm5/core/ResultMetadataType';
import { BrowserQRCodeReader } from '@zxing/library/esm5/browser/BrowserQRCodeReader';
import MobilePage from '../components/MobilePage.vue';

export default {
  components: { MobilePage },
  data: () => ({
    cameraAllowed: false,
    reader: new BrowserQRCodeReader(),
  }),
  watch: {
    async cameraAllowed(value) {
      if (!value) {
        this.reader.reset();
        return;
      }

      let data;
      do {
        if (data) {
          // eslint-disable-next-line no-await-in-loop
          await this.$store.dispatch('alert', {
            title: 'Scanned QR code is wrong',
            text: 'Please make sure to scan a QR code generated by the Bæse æpp',
          });
        }
        // eslint-disable-next-line no-await-in-loop
        const result = await this.reader.decodeFromInputVideoDevice(
          undefined,
          this.$refs.qrCodeVideo,
        );
        data = Buffer.from(result.resultMetadata.get(ResultMetadataType.BYTE_SEGMENTS)[0]);
      } while (data.length !== 15);

      this.$store.commit('addFollower', {
        id: data.toString('base64'),
        name: prompt('Name this device') || 'Unnamed',
      });
      this.$router.push({ name: 'settings-remote-connection' });
    },
  },
  async mounted() {
    if (process.env.IS_CORDOVA) {
      const { permissions } = window.cordova.plugins;
      await new Promise((resolve, reject) =>
        permissions.requestPermission(
          permissions.CAMERA,
          ({ hasPermission }) =>
            (hasPermission ? resolve() : reject(new Error('Denied to use the camera'))),
          reject,
        ));
      this.cameraAllowed = true;
      return;
    }

    if (navigator.permissions) {
      const status = await navigator.permissions.query({ name: 'camera' });
      this.cameraAllowed = status.state !== 'denied';
      status.onchange = () => {
        this.cameraAllowed = status.state !== 'denied';
      };
      return;
    }

    this.cameraAllowed = true;
  },
  beforeDestroy() {
    this.reader.reset();
  },
};
</script>

<style lang="scss" scoped>
@import '~@aeternity/aepp-components/dist/mixins.scss';

.settings {
  @include phone {
    /deep/ .panel .content {
      margin-bottom: 0;
      overflow: hidden;
      position: relative;
    }
  }

  .permission-denied {
    text-align: center;
    line-height: 1.56;
    padding: 60px 20px;
    font-size: 18px;
  }

  video {
    display: block;
    width: 100%;
    object-fit: cover;

    @include phone {
      position: absolute;
      height: 100%;
    }
  }
}
</style>
<style src="./Settings.scss" lang="scss" scoped />
