<template>
  <div />
</template>

<script>
export default {
  async mounted() {
    let data;
    do {
      if (data) {
        // eslint-disable-next-line no-await-in-loop
        await this.$store.dispatch('alert', {
          title: 'Scanned QR code is wrong',
          text: 'Please make sure to scan a QR code generated by the Base æpp',
        });
      }

      try {
        // eslint-disable-next-line no-await-in-loop
        data = await this.$store.dispatch('modals/readQrCode', { title: 'Remote Connection' });
      } catch (e) {
        this.$router.push({ name: 'settings-remote-connection' });
        return;
      }

      data = Buffer.from(data, 'base64');
    } while (data.length !== 15);

    this.$store.commit('addFollower', {
      id: data.toString('base64'),
      name: prompt('Name this device') || 'Unnamed',
    });
    this.$router.push({ name: 'settings-remote-connection' });
  },
};
</script>
