on:
  workflow_call:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - run: npm ci
      working-directory: 'backend'
    - run: npm test
      working-directory: 'backend'
    - run: npm ci --legacy-peer-deps # TODO: remove --legacy-peer-deps after updating dependencies
    - run: docker compose up middleware -d --wait
    - run: ./docker-compose/init-state.mjs
    - run: npm test
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: failure()
      with:
        commit_message: "fixme: update e2e screenshots"
        file_pattern: 'tests/e2e/*.png'
    - run: docker compose logs
      if: always()
