name: Aepp-Base Build

on:
  push:
    branches: [ master, develop ]
    tags:
      - 'v*'
  pull_request: 
    branches: [ master, develop ]

jobs:
  main:
    runs-on: ubuntu-latest
  
    name: Build Docker
    steps:

      - uses: actions/checkout@v2
  
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push Docker image
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["aeternity/aepp-base:latest","aeternity/aepp-base:'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["aeternity/aepp-base:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: Build and push Docker image
        id: build_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: nginx.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
